# Generated by Django 4.1.2 on 2022-10-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=256)),
                ('cooperative', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=256)),
                ('variety', models.CharField(max_length=256)),
                ('altitude', models.CharField(max_length=256)),
                ('soil', models.CharField(max_length=256)),
                ('process', models.CharField(max_length=256)),
                ('total_members', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Growerscoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperative', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('total_factories', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
