# Generated by Django 4.1.2 on 2022-10-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_number', models.PositiveIntegerField(default=0, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('id_no', models.PositiveIntegerField(default=0, editable=False, unique=True)),
                ('address', models.CharField(max_length=256)),
                ('farm_size', models.CharField(max_length=256)),
                ('variety', models.CharField(choices=[('SL28', 'SL28'), ('SL34', 'SL34'), ('Ruiru 11', 'Ruiru 11'), ('Batian', 'Batian')], default='Batian', max_length=200)),
                ('contact', models.PositiveIntegerField(default=0, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Deactivated', 'Deactivated'), ('Activated', 'Activated')], default='Activated', editable=False, max_length=11)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
